/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef spell_CONSTANTS_H
#define spell_CONSTANTS_H

#include "spell_types.h"



class spellConstants {
 public:
  spellConstants();

};

extern const spellConstants g_spell_constants;



#endif
